Add a couple of unit tests
npatsakula/bitmap pull request #5
Opened 2020-11-04 14:48 UTC by rudlorenz

2020-11-04 15:07 UTC, npatsakula requested changes
:kissing_heart:

2020-11-04 15:07 UTC, npatsakula commented on src/lib.rs
> +    #[test]
```suggestion
    #[test]
    fn value_write() {
        let mut bitmap = DynBitmap::contained(32);
        let mut cursor: std::io::Cursor<Vec<u8>> = Default::default();

        for i in 0 .. bitmap.bits_capacity()-1 {
            bitmap.set(i).unwrap();
            bitmap.write(&mut cursor).unwrap();

            assert_eq!(
                ((1u32 << i as u32 + 1) - 1).to_le_bytes().as_ref(),
                cursor.get_ref().as_slice(),
            );

            cursor.set_position(0);
        }
    }
```

2020-11-04 15:07 UTC, npatsakula commented on src/lib.rs
> +        let position_in_byte = Self::position_in_byte(bit_index);
:sunglasses:

2020-11-04 15:12 UTC, rudlorenz commented on src/lib.rs
> +        let position_in_byte = Self::position_in_byte(bit_index);
`position_in_byte` already returns a `u8`

2020-11-05 05:16 UTC, rudlorenz commented on src/lib.rs
> +    #[test]
+

2020-11-05 08:47 UTC, npatsakula approved these changes

2020-11-05 08:47 UTC, merged